- hosts: all
  tasks:
    - name: Show config parameter - vscode_setting_dir
      debug:
        var: vscode_setting_dir

    # Remove dotfiles in HOME directory
    - name: Remove dotfiles in HOME directory
      file:
        path: "{{ ansible_env.HOME }}/{{ item }}"
        state: absent
      with_items:
        - .tmux
        - .zsh
        - .zshrc
    # Install dotfiles in HOME directory
    - name: Install dotfiles in HOME directory
      file:
        src: "{{ ansible_env.PWD }}/home/{{ item }}"
        path: "{{ ansible_env.HOME }}/{{ item }}"
        state: link
      with_items:
        - .tmux
        - .zsh
        - .zshrc
    - name: Get plugin manager "antigen" for zsh
      get_url:
        url: https://git.io/antigen
        dest: "{{ ansible_env.HOME }}/.zsh/antigen.zsh"
        mode: '0644'

    # vscode
    - name: Remove previous vscode config file
      file:
        path: "{{ vscode_setting_dir }}/{{ item }}"
        state: absent
      with_items:
        - settings.json
        - keybindings.json
    - name: Create a Symbolic link vscode config file
      file:
        src: "{{ ansible_env.PWD }}/vscode/{{ item }}"
        path: "{{ vscode_setting_dir }}/{{ item }}"
        state: link
      with_items:
        - settings.json
        - keybindings.json
    - name: Install extensions
      command: "code --install-extension {{ item }}"
      with_lines: cat vscode/extensions.txt
